### ISSUE TITLE
Eval code Error

### ISSUE THREAD

**Issue by hitcslj** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#5]
Hi, I have some problem when I eval the code, The error message is as follows.

## trainval data.

```bash
2023-03-06 23:15:59,690 - mmdet - INFO - Epoch [1][14050/14065] lr: 2.000e-04, e
ta: 7 days, 18:42:48, time: 2.075, data_time: 0.027, memory: 14379, loss_occ: 0.
1698, loss: 0.1698, grad_norm: 0.2118
2023-03-06 23:16:30,723 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>           ] 4712/6019, 6.7 task/s, elap
sed: 706s, ETA:   196sERROR:torch.distributed.elastic.multiprocessing.api:failed
 (exitcode: -9) local_rank: 1 (pid: 3636) of binary: /home/aiia611/anaconda3/env
s/open-mmlab/bin/python
Traceback (most recent call last):
  File "/home/aiia611/anaconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 19
4, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aiia611/anaconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 87
, in _run_code
    exec(code, run_globals)

```

**Comment by WillKen** [comment]
same problem

**Comment by 1349949** [comment]
More error message printed? Or is that all?

**Comment by qihao-plus** [comment]
```
# bevformer_small_occ.py
# epoch 24 trained locally on 8x3090 (24GiB each)
# OOM for bevformer_base_occ.py
===> per class IoU of 6019 samples:                                                                                                                                                                         
===> others - IoU = 6.5                                                                                                                                                                                     
===> car - IoU = 36.91                                                                                                                                                                                      
===> truck - IoU = 11.94                                                                                                                                                                                    
===> trailer - IoU = 36.19                                                                                                                                                                                  
===> bus - IoU = 41.55                                                                                                                                                                                      
===> construction_vehicle - IoU = 11.18                                                                                                                                                                     
===> bicycle - IoU = 19.11                                                                                                                                                                                  
===> motorcycle - IoU = 17.57                                                                                                                                                                               
===> pedestrian - IoU = 16.19                                                                                                                                                                               
===> traffic_cone - IoU = 15.53                                                                                                                                                                             
===> barrier - IoU = 28.98                                                                                                                                                                                  
===> driveable_surface - IoU = 51.61                                                                                                                                                                        
===> other_flat - IoU = 30.36                                                                                                                                                                               
===> sidewalk - IoU = 30.89                                                                                                                                                                                 
===> terrain - IoU = 25.63                                                                                                                                                                                  
===> manmade - IoU = 16.26                                                                                                                                                                                  
===> vegetation - IoU = 15.3                                                                                                                                                                                
===> mIoU of 6019 samples: 24.22 
```

**Comment by YWonchall** [comment]
> 

Hi,I want to know how much GPU memory does baseline small need? Thank you!

**Comment by NotACracker** [comment]
> 

Hi，I'm confused about the predicted label name mapping, the official mapping of nuscenes should be 0-16 corresponding to barrier, bicyble, bus, car, const. veh., motorcycle, pedestrain, traffic cone, trailer, truck, drive. suf., other flat, sidewalk, terrian, manmade, vegetation. However, in the code and your results, it's not the same order. Is there any problem here?

**Comment by 1349949** [comment]
> 

This is a output bug. We fix it now. 
Our ground-truth data have the same label order with nuScenes-lidarseg.

**Comment by 1349949** [comment]
> > @qihao-plus
> 
> Hi，I'm confused about the predicted label name mapping, the official mapping of nuscenes should be 0-16 corresponding to barrier, bicyble, bus, car, const. veh., motorcycle, pedestrain, traffic cone, trailer, truck, drive. suf., other flat, sidewalk, terrian, manmade, vegetation. However, in the code and your results, it's not the same order. Is there any problem here?

This is a eval output bug. We fix it now.
Our ground-truth data have the same label order with nuScenes-lidarseg.

**Comment by hitcslj** [comment]
solved in [issue6](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/issues/6)

**Comment by qihao-plus** [comment]
after fix
```
# bevformer_small_occ.py
# epoch 24 trained locally on 8x3090 (24GiB each)
# OOM for bevformer_base_occ.py
===> per class IoU of 6019 samples:
===> others - IoU = 6.49
===> barrier - IoU = 36.92
===> bicycle - IoU = 11.97
===> bus - IoU = 36.22
===> car - IoU = 41.55
===> construction_vehicle - IoU = 11.18
===> motorcycle - IoU = 19.1
===> pedestrian - IoU = 17.58
===> traffic_cone - IoU = 16.18
===> trailer - IoU = 15.53
===> truck - IoU = 29.0
===> driveable_surface - IoU = 51.62
===> other_flat - IoU = 30.37
===> sidewalk - IoU = 30.91
===> terrain - IoU = 25.64
===> manmade - IoU = 16.27
===> vegetation - IoU = 15.31
===> mIoU of 6019 samples: 24.22

######## F score: 0.567128882874676 #######
```
