### ISSUE TITLE
visualization error

### ISSUE THREAD

**Issue by polo5** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#51]
Hello,

I cannot run your utils/vis.py script. I get the error:

```
Traceback (most recent call last):
  File "utils/vis.py", line 194, in <module>
    vis_nuscene()
  File "utils/vis.py", line 175, in vis_nuscene
    vis = show_point_cloud(points=points, colors=True, points_colors=pcd_colors, voxelize=True, obj_bboxes=None,
  File "utils/vis.py", line 110, in show_point_cloud
    opt.background_color = np.asarray([1, 1, 1])
AttributeError: 'NoneType' object has no attribute 'background_color'
```

Any idea? I couldn't find the open3d verison you use. Thanks

**Comment by ChonghaoSima** [comment]
My experience is that the file is not read correctly and some variables become nonetype. Please check the file loading path and related stuff.
